# -*- coding: utf-8 -*-
"""Reddit data scrape 2.0

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQ_t0VnHWzP6kGtfioRE_DBQndm6-UEE
"""

!pip install praw

import praw #wrapper for scrapping reddit data
#credentials to scrape
reddit = praw.Reddit(client_id='##',
                     client_secret='##',
                     password='##',
                     user_agent='Build a flare detector.',
                     username='##')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Reddit_in =reddit.subreddit('India') # Subreddit in reddit

flairs = ['AskIndia','Non-Political','Scheduled','Photography','Science/Technology','Politics',
          'Business/Finance','Policy/Economy','Sports','Food'] #different flairs in the India subreddit

data = []
for flair in flairs:
   x = Reddit_in.search(flair, limit=1000)
   for post in x:
      topcomments = ' '
      post.comments.replace_more(limit=0) #we only want top comments
      for comment in post.comments:
          topcomments = topcomments + ' ' + (comment.body)
      data.append([flair,post.id,post.title,post.selftext,post.url,topcomments])

df = pd.DataFrame(data,columns=['Flair','ID','Title','Body','URL','Comments'])

r,c = df.shape
print(r,c)

from google.colab import files
df.to_csv('finalflaredata2.csv') 
files.download('finalflaredata2.csv')

ypost = reddit.submission(url='https://www.reddit.com/r/india/comments/g7rtx9/sambit_patra_caught_spreading_fake_news_to/')

topcomments=''
ypost.comments.replace_more(limit=0) #we only want top comments
for comment in ypost.comments:
  topcomments = topcomments + ' ' + comment.body

topcomments
#ypost.subreddit.display_name

topcomments

